apiVersion : apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: admin19.azurecr.io/delivery
          ports:
            - containerPort: 8080
